### ISSUE TITLE
How to put the header on the top of the tableview?

### ISSUE THREAD

**Issue by sseen** [maniak-dobrii/iOS-solutions#1]
Thanks for your project, your code running perfectly, I just make a new project use your code for my test. The result is the header view is below of the table cell.
![ios simulator screen shot 2015 2 8 2 59 28](https://cloud.githubusercontent.com/assets/3367000/6095702/1a8a03b0-afa3-11e4-95bb-bfede17a9a8e.png)

**Comment by maniak-dobrii** [comment]
Looks like it's a tableViewFooter. Guess it's from IB, sometimes (maybe always) if you drag some view on UITableView it could (maybe do) assigns it as tableViewFooter, so check that first.
