### ISSUE TITLE
No more setter magic?

### ISSUE THREAD

**Issue by allaire** [maniak-dobrii/iOS-solutions#2]
Hey @maniak-dobrii ,

Do you confirm on your side that tableHeaderView now automatically adjust its height when set, so we don't need the setter magic anymore (https://github.com/maniak-dobrii/iOS-solutions/blob/master/TableHeaderView%2BAutolayout/TableHeaderView%2BAutolayout/ViewController.m#L64).

I'm using swift 1.x on iOS 8.

Thanks!

**Comment by maniak-dobrii** [comment]
The point of re-setting tableHeaderView is to adjust its height. And I'm not sure if it started to update height without re-setting.

**Comment by maniak-dobrii** [comment]
iOS 10 - magic still required
