### ISSUE TITLE
Suggestion: On adding new item it should scroll down to bottom.

### ISSUE THREAD

**Issue by niteshborad** [maniak-dobrii/iOS-solutions#3]
Update 'onIncButtonTapped' method to following code. This will scroll down the collection view to bottom on adding new item.

```
    func onIncButtonTapped(_ sender: AnyObject?) {
        updateNumberOfItems(dif: 1)
        self.collectionView?.scrollToItem(at: IndexPath.init(row: numberOfItems-1, section: 0), at: UICollectionViewScrollPosition.bottom, animated: true)
    }
```

**Comment by maniak-dobrii** [comment]
Thank you for you input, but this goes out of scope of this demo and people might want different behavior for that. For example, for my case it was more appropriate to keep the same behavior as plain UITableView at the same time addressing the "few cells at the bottom" issue. I see cases where it is appropriate to scroll to the top or to the bottom as well, but the plot of this demo is exactly "snap cells to the bottom if there are not too much of them" .
