### ISSUE TITLE
How can we get dynamic cell heights using auto layout as we do in tableview with UITableViewAutomaticDimension?

### ISSUE THREAD

**Issue by niteshborad** [maniak-dobrii/iOS-solutions#4]

**Comment by maniak-dobrii** [comment]
**Copy from SO:**
I'd suggest against autolayout inside UITableView/UICollectionView cells, but if you still need this you can do that in a number of ways, for collection view I've found that answer: stackoverflow.com/q/25895311/1032151 Usually, for UITableView you have a static "sizing cell" that you configure with your data and calculate height, with collection views it works differently, but with the layout I suggest, you may use the same concept.
